# Generated by Django 4.2.4 on 2023-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverytype',
            name='delivery_price',
            field=models.FloatField(),
        ),
    ]
