# Generated by Django 4.2.4 on 2023-11-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20220106_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizeandquantity',
            name='size',
            field=models.CharField(choices=[('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('S', 'short'), ('M', 'medium'), ('L', 'large'), ('XL', 'extra large'), ('XXL', 'extra x large')], max_length=30),
        ),
    ]
