# Generated by Django 5.0.2 on 2025-05-13 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment_details',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='payment_details',
            name='amount_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('1', 'cash on delievery'), ('2', 'SSLCOMMERZ')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pyments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
