# Generated by Django 4.2.4 on 2023-12-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliverytype_delivery_price'),
        ('order', '0002_remove_order_order_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliverytype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.payment_details'),
        ),
        migrations.AlterField(
            model_name='payment_details',
            name='status',
            field=models.CharField(blank=True, choices=[('succeed', 'Succeed'), ('failed', 'Failed'), ('pending', 'Pending')], default=None, max_length=32, null=True),
        ),
    ]
